### ISSUE TITLE
in samsung galaxy 10+

### ISSUE THREAD

**Issue by developers420** [M1Lr05/IsTheApp#14]
hello. in Samsung galaxy 9+ working perfect but in Samsung galaxy 10+ inside parents after login crash, and 3 option not working in all phone .
1 . Notifications received: Whatsapp, Instagram, Messenger.
2. call recoder.
3. after password settings then app not open. app crash.
other all options is working good.
please check this. thankyou.

**Comment by M1Lr05** [comment]
Subsection 3 corrected.
