### ISSUE TITLE
kotlin compiler & java compiler warnings stopped working

### ISSUE THREAD

**Issue by nani22336** [M1Lr05/IsTheApp#16]
![Capture](https://user-images.githubusercontent.com/57306856/68087226-b6083580-fe79-11e9-91b7-61d11dcbf5da.JPG)
these errors are stopping from running the app successfully
only keylogger and messaging services are active if i build the apk

**Comment by M1Dr05** [comment]
> ![Capture](https://user-images.githubusercontent.com/57306856/68087226-b6083580-fe79-11e9-91b7-61d11dcbf5da.JPG)
> these errors are stopping from running the app successfully
> only keylogger and messaging services are active if i build the apk

try to compile with gradle version 3.2.1
classpath 'com.android.tools.build:gradle:3.2.1'

**Comment by M1Lr05** [comment]
try to compile with gradle version 3.2.1
classpath 'com.android.tools.build:gradle:3.2.1'

**Comment by nani22336** [comment]
K sir thank you so much
