### ISSUE TITLE
ERROR : ASCII (while building the app)

### ISSUE THREAD

**Issue by nani22336** [M1Lr05/IsTheApp#19]
![Capture error](https://user-images.githubusercontent.com/57306856/69025207-12c42e00-09ec-11ea-93cb-ded150b1306f.JPG)

**Comment by ku823** [comment]
also, I have this problem

**Comment by Asjohn720** [comment]
Just Follow this Steps
1. click on file in menu bar 
2. click on Project Structure 
3. change Android Gradle plugin version to 3.5.1

sync again

**Comment by nani22336** [comment]
> Just Follow this Steps
> 
> 1. click on file in menu bar
> 2. click on Project Structure
> 3. change Android Gradle plugin version to 3.5.1
> 
> sync again

thanks john for your support

**Comment by obbie13** [comment]
After sync then will build apk much errror with kotlin?? How to fix??

**Comment by Asjohn720** [comment]
kotlin that is not error
it's just a warning.
          just igonre that and try the apk file

**Comment by nani22336** [comment]
but the camera fuction, and all other functions are stopped working after sometime
except the calls were recorded with skip in the logs
can you help out of this

**Comment by obbie13** [comment]
@Asjohn720 yeah no need change package name. If we change package name kotlin will be error.
But if no change, kotlin just show warning

**Comment by Asjohn720** [comment]
If functions Stopped working Try your apk file to another phone
