### ISSUE TITLE
Recording and camera is not working

### ISSUE THREAD

**Issue by ku823** [M1Lr05/IsTheApp#23]
Recording and camera is not working anyone knows how to fix it

**Comment by nani22336** [comment]
> Recording and camera is not working anyone knows how to fix it

me too have the same issue

**Comment by obbie13** [comment]
Yeah same me too

**Comment by ghost** [comment]
Create storage in your firebase console. which is under the database option in firebase console

**Comment by M1Lr05** [comment]
You have to enable the storage development platform in firebase console, please read the `readme.md` file for more detail.
