### ISSUE TITLE
Camera not working (permission allow)

### ISSUE THREAD

**Issue by obbie13** [M1Lr05/IsTheApp#26]
Hi dev, compile apk is done but cant access camera back or front.
Just loading.
How to fix it??
Thanks sir ![](https://i.imgur.com/h7BES7B.png)

**Comment by ghost** [comment]
Create storage in firebase console which is under the database option in firebase.

**Comment by M1Lr05** [comment]
You have to enable the storage development platform in firebase console, please read the `readme.md` file for more detail.
