### ISSUE TITLE
Some bugs Found..!!!

### ISSUE THREAD

**Issue by MohdSaleh** [M1Lr05/IsTheApp#27]
--- Recording is not working properly => after recording the file is not shown 
---Get Photo is loading not showing any response
--- Notification reading => not working
--- Call logs are not visible 
--- SMS are not visible 

--- Location Works Fine and its GOOD
--- KeyLog Works Fine looks GOOD

**Comment by M1Lr05** [comment]
You have to enable the storage development platform in firebase console, please read the `readme.md` file for more detail.
