### ISSUE TITLE
firebase real-time database rules error

### ISSUE THREAD

**Issue by Mera-balou** [M1Lr05/IsTheApp#29]
I managed to compile apk, but when i want to add the rules below in firebase real-time database, i received an error :
```
{
"rules": {
".read": "auth != null",
".write": "auth != null"
}
}
```
> Line 1: mismatched input '{' expecting {'function', 'import', 'service', 'rules_version'}

Do you have any idea how to fix this?
@niranjanimalka98 @M1Dr05

**Comment by RamyaArumugam186** [comment]
Hi in firebase account go to database and in Rules edit it..

**Comment by Mera-balou** [comment]
My bad, i was in Cloud Firestore database....
Changed to realtime database and is working.

Thanx!
