### ISSUE TITLE
compile apk error

### ISSUE THREAD

**Issue by dimension-drifter** [M1Lr05/IsTheApp#4]
When i try to compile apk in android studio it says an error has occurred and i am not able to compile my app so please help me. I am a newbie on this websit and i dont know coding and programming. please help me by compiling apk for me.
 Screenshot of error.
![image](https://user-images.githubusercontent.com/47204587/52123163-41366f80-264b-11e9-82af-dfc677edb794.png)
![image](https://user-images.githubusercontent.com/47204587/52123189-54493f80-264b-11e9-8224-d328ef66256c.png)
![image](https://user-images.githubusercontent.com/47204587/52123196-5ad7b700-264b-11e9-8917-1777c5235f3c.png)
Please Help ME
I will be grateful to you.

**Comment by M1Lr05** [comment]
please read the readme file in the build this project section.
you have to create a project in firebase and synchronize it with the applications
https://firebase.google.com/docs/android/setup?hl=en-419#manually_add_firebase
