### ISSUE TITLE
Manage to work

### ISSUE THREAD

**Issue by jag-chichria** [M1Lr05/IsTheApp#7]
Hey mate, 

everything is working including initial user location, sms. but when Child app goes background  (Oreo or plus), it stops sending information to firebase. 
And, What is Package Social Netweok and how to set it up?

Any help will be helpful.

thanks

**Comment by nitrogue07** [comment]
how were you able to compile parent

**Comment by jag-chichria** [comment]
What the error do you see or get during compile?

**Comment by nitrogue07** [comment]
fixed it it was something about firebase and github dependencies

**Comment by shailandraRajput** [comment]
Call recording working For you?
If yes can you please guide me?

**Comment by nitrogue07** [comment]
call recording cannot work on andoid 9+
its limited by the operating system
